# ----------------------------------------------------------------------------
#   Configuration file for the tk_utils_core module 
# ----------------------------------------------------------------------------
debug = false
dependencies = [
    "python>=3.12",
    "yfinance",
    "pandas",
    "numpy",
    "requests",
    "ruamel.yaml",
    "pydantic>=2,<3",
]

[pretty_errors]
pretty_errors = true
line_number_first = false
display_link = true

[doctests]
print_docstring = false
print_examples = true
print_hdr = true
print_mod = false
verbose = false
compileflags = false

[pp]
color=""
indent=""
pretty=true
sort_dicts=false
depth=""
underscore_numbers=true
width=40
compact=false

[pycharm]
validate_paths=true
prjname="toolkit"
# All paths are relative to the PyCharm project folder
[pycharm.paths]
root="."
backup="./_backup"
dropbox="./_dropbox"
venv="./.venv"
idea="./.idea"
tk_utils="./tk_utils"
toolkit_config="./toolkit_config.py"
tk_utils_config="./tk_utils/config.toml"
dropbox_zip="./_dropbox/tookit.zip"

[github]
[github.tk_utils]
user="brenoschmidt"
repo="toolkit"
branch="main" # Should not be blank
base="tk_utils"
modules=[
    "__init__.py",
    "setup.py",
    ]
[github.tk_utils_core]
user="brenoschmidt"
repo="tk_utils_core"
branch=""

[dropbox]
url=""

